module.exports = {
  CONNECTION: 'connection',
  DISCONNECT: 'disconnect',
  USER_ONLINE: 'user:online',
  USER_OFFLINE: 'user:offline',
  PRESENCE_GET: 'presence:get',
  CONVERSATION_JOIN: 'conversation:join',
  CONVERSATION_LEAVE: 'conversation:leave',
  MESSAGE_SEND: 'message:send',
  MESSAGE_NEW: 'message:new',
  MESSAGE_DELIVERED: 'message:delivered',
  MESSAGE_READ: 'message:read',
  MESSAGE_READ_UPDATE: 'message:read:update',
  CONVERSATION_READ: 'conversation:read',
  TYPING_START: 'typing:start',
  TYPING_STOP: 'typing:stop',
};
