module.exports = {
  CONNECTION: 'connection',
  DISCONNECT: 'disconnect',
  USER_ONLINE: 'user:online',
  USER_OFFLINE: 'user:offline',
  PRESENCE_GET: 'presence:get',
  CONVERSATION_JOIN: 'conversation:join',
  CONVERSATION_LEAVE: 'conversation:leave',
  MESSAGE_SEND: 'message:send',
  MESSAGE_NEW: 'message:new',
  MESSAGE_DELIVERED: 'message:delivered',
  MESSAGE_READ: 'message:read',
  MESSAGE_READ_UPDATE: 'message:read:update',
  CONVERSATION_READ: 'conversation:read',
  MESSAGE_EDIT: 'message:edit',
  MESSAGE_DELETE: 'message:delete',
  MESSAGE_UPDATED: 'message:updated',
  MESSAGE_DELETED: 'message:deleted',
  TYPING_START: 'typing:start',
  TYPING_STOP: 'typing:stop',
  GROUP_UPDATED: 'group:updated',
  GROUP_MEMBER_ADDED: 'group:member:added',
  GROUP_MEMBER_REMOVED: 'group:member:removed',
  GROUP_ADMIN_ADDED: 'group:admin:added',
  GROUP_ADMIN_REMOVED: 'group:admin:removed',
  GROUP_LEFT: 'group:left',
};
